image: bjodah/dockerfile-bjodah-scicomp:14.04c
git:
    path: github.com/bjodah/pyneqsys
env:
  - MY_SERVER=pyneqsys@hera.physchem.kth.se
script:
  - if [[ "$DRONE_BRANCH" =~ ^v[0-9]+.[0-9]?* ]]; then export PYNEQSYS_RELEASE_VERSION=$DRONE_BRANCH; echo ${PYNEQSYS_RELEASE_VERSION} | tail -c +2 > __conda_version__.txt; fi
  - pip install --user -r requirements.txt
  - pip3 install --user -r requirements.txt
  - PYTHONPATH=$(pwd) ./scripts/run_tests.sh --cov pyneqsys --cov-report html
  - python2 setup.py sdist
  - ./scripts/generate_docs.sh
  - ssh "${MY_SERVER}" "mkdir -p ~/public_html/$DRONE_BRANCH" && scp -r doc/ dist/* htmlcov/ ${MY_SERVER}:~/public_html/$DRONE_BRANCH
  - touch doc/_build/html/.nojekyll
  - git config --global user.name "drone"
  - git config --global user.email "drone@hera.physchem.kth.se"
  - if [[ "$DRONE_BRANCH" == "master" ]]; then ./scripts/github_upload.sh doc/_build/html bjodah pyneqsys gh-pages; fi
