name: pyneqsys
channels:
  - bjodah
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy >1.7
  - scipy >=0.19.1
  - sym >=0.3.1
  - sympy >=1.1.1
  - matplotlib >=1.5.3
  - notebook
  - nbconvert
  - pykinsol
  - levmar
