package:
    name: pyneqsys
    version: 0.3.0.dev1

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - python
        - numpy
    run:
        - python
        - numpy
        - sympy
        - scipy
        - pyodesys

test:
    imports:
        - pyneqsys
    requires:
        - nose
    commands:
        - nosetests pyneqsys

about:
    home: https://github.com/bjodah/pyneqsys
    license: BSD
