package:
    name: pyneqsys
    version: 0.1.0.git

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - sympy
        - scipy
        - pyodeint
        - pygslodeiv2
        - pycvodes

test:
    imports:
        - pyneqsys
    requires:
        - pytest
        - scipy
        - pyodeint
        - pygslodeiv2
        - pycvodes

about:
    home: https://github.com/bjodah/pyneqsys
    license: BSD
