package:
    name: pyneqsys
    version: 0.3.0.dev1

source:
    path: ../

build:
    number: 0

requirements:
    build:
        - python
        - numpy
    run:
        - python
        - numpy
        - sympy
        - scipy
        - pyodesys
        - symengine

test:
    imports:
        - pyneqsys
    requires:
        - pytest
    commands:
        - py.test --pyargs pyneqsys

about:
    home: https://github.com/bjodah/pyneqsys
    license: BSD
