{% set name = "pyneqsys" %}
{% set version = "0.6.0.git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy >1.7
    - scipy >=0.19.1
    - sym >=0.3.1
    - sympy >=1.1.1
    - matplotlib >=1.5.3

test:
  imports:
    - {{ name }}
  requires:
    - pytest
    - python-symengine
    - symcxx
    - pysym
    - pykinsol
    - ipopt
    - levmar
  commands:
    - pytest --pyargs {{ name }}

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Solve symbolically defined systems of non-linear equations numerically.'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
